day_close: '24:00'
day_open: 00:00
days_ahead: 14
id_cuadro: '4'
match_rules:
- clubs:
  - HOP BRAUNSCHWEIG
  - HOP WOLFENBÜTTEL
  - HOP WENDEBURG
  enabled: true
  min_frei: 1
  name: PlayMatch 3 Tage
  niveau_min: 2
  stunden_voraus: 72
  weekdays: []
  zeit_bis: '20:30'
  zeit_von: '16:00'
max_messages: 10
notify_after_errors: 2
notify_on_error: true
rules:
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 90
  name: Sa-So Vormittags
  weekdays:
  - Sa
  - So
  windows:
  - from: 09:00
    to: '15:00'
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 90
  name: Mo-Do Nachmittags
  weekdays:
  - Mo
  - Di
  - Mi
  - Do
  windows:
  - from: '16:00'
    to: '22:00'
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 60
  name: Fr Training
  weekdays:
  - Fr
  windows:
  - from: '14:00'
    to: '18:00'
- courts: []
  duration: 90
  enabled: false
  name: Test
  weekdays:
  - Mo
  windows:
  - from: 04:00
    to: 06:00
- name: Di/Mi Abend
  enabled: true
  weekdays:
  - Di
  - Mi
  windows:
  - from: '19:00'
    to: '20:00'
  - from: '21:00'
    to: '22:00'
  duration: 60
  courts: []
token_expires: '2026-10-30'
token_warn_days: 14
