day_close: '24:00'
day_open: 00:00
days_ahead: 7
id_cuadro: '4'
max_messages: 10
notify_on_error: true
token_expires: '2026-10-30'
token_warn_days: 7
rules:
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 90
  name: Wochenende vormittags
  time_from: 08:00
  time_to: '15:00'
  weekdays:
  - Sa
  - So
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 90
  name: Nachmittags
  time_from: '16:00'
  time_to: '22:00'
  weekdays:
  - Mo
  - Di
  - Mi
  - Do
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 60
  name: Freitag
  time_from: '14:00'
  time_to: '22:00'
  weekdays:
  - Fr
- courts: []
  duration: 90
  enabled: true
  name: Test
  time_from: 04:00
  time_to: 06:00
  weekdays:
  - Mo
