day_close: '24:00'
day_open: 00:00
days_ahead: 7
id_cuadro: '4'
max_messages: 10
notify_on_error: true
rules:
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 90
  name: Wochenende vormittags
  time_from: 09:00
  time_to: '13:00'
  weekdays:
  - Sa
  - So
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 90
  name: Nachmittags
  time_from: '16:00'
  time_to: '22:00'
  weekdays:
  - Mo
  - Di
  - Mi
  - Do
- courts:
  - '16'
  - '17'
  - '13'
  - '14'
  - '15'
  duration: 90
  name: Freitag
  time_from: '14:00'
  time_to: '22:00'
  weekdays:
  - Fr
- name: Test
  weekdays:
  - Mo
  - Di
  - Mi
  - Do
  - Fr
  - Sa
  - So
  time_from: 08:00
  time_to: '10:00'
  duration: 90
  courts: []
